/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DivinationCard: typeof import('./src/components/DivinationCard/DivinationCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Log: typeof import('./src/components/Log/Log.vue')['default']
    MiniItemIcon: typeof import('./src/components/MiniItemIcon/MiniItemIcon.vue')['default']
    Pack: typeof import('./src/components/Pack/Pack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/slider/slider.vue')['default']
    Stash: typeof import('./src/components/Stash/Stash.vue')['default']
    Workbench: typeof import('./src/components/Workbench/Workbench.vue')['default']
  }
}
